#!/bin/bash
# Begin LSF Directives, run mark_models to find top-r2 models
#BSUB -P bif138
#BSUB -W 8:00
#BSUB -q killable
#BSUB -nnodes 1
#BSUB -J mark_models1
#BSUB -o mark_models1.%J
#BSUB -e markmodels1_err.%J

source /gpfs/alpine/proj-shared/bif138/rogersdd/env2.sh

for i in {1,3,4,5,6,7,9,10,11}; do

    echo $i
    cd /gpfs/alpine/proj-shared/bif138/chr${i}

    while read tile; do
    echo $tile
    python3 mark_models.py $tile

    done < tiles.done

done
